### ISSUE TITLE
Forked process not killed after build or after specified task

### ISSUE THREAD

**Issue by davishyer** [psxpaul/gradle-execfork-plugin#9]
I'm attempting to use this plugin to start a few servers necessary to run full browser tests. I can successfully start both servers, and move on to the tests, but after the tests are run, the servers remain active. I noticed a similar issue in #1 but the suggestion to set `org.gradle.daemon=false` didn't work.

Here is an example gradle task that I'm defining. Based on the documentation around the `stopAfter` property, I assumed that the servers would be killed after the task is complete:
```groovy
task runTests(dependsOn: ['startBackend', 'startFrontend']) {
  doLast {
    // run tests
  }
}

task startBackend(type: com.github.psxpaul.task.ExecFork) {
  commandLine = './my_jar.jar'
  workingDir = "$project.rootDir/api/build/libs"
  waitForOutput = "Started ApplicationKt"
}

task startFrontend(type: com.github.psxpaul.task.ExecFork) {
  commandLine = './start.ui.sh'
  workingDir = "$project.rootDir"
  waitForOutput = "Compiled successfully"
}
```

Since the above wasn't working, I attempted to specify when the servers should be stopped using the `stopAfter` property. Again, after the task completes, the servers are both still running.
```groovy
task runTests(dependsOn: ['startBackend', 'startFrontend']) {
  doLast {
    // run tests
  }
}

task startBackend(type: com.github.psxpaul.task.ExecFork) {
  commandLine = './my_jar.jar'
  workingDir = "$project.rootDir/api/build/libs"
  waitForOutput = "Started ApplicationKt"
  stopAfter =runTests
}

task startFrontend(type: com.github.psxpaul.task.ExecFork) {
  commandLine = './start.ui.sh'
  workingDir = "$project.rootDir"
  waitForOutput = "Compiled successfully"
  stopAfter = runTests
}
```

I've been able to kill the servers myself by finding the pid based on the port each server runs on and killing it. However, based on the documentation provided, I was under the assumption that I wouldn't need to do this. It's entirely possible I have something configured incorrectly, but figured I'd post in case others run into the same issue. For reference, I ended up killing the servers with `lsof -i tcp:${port} | awk 'NR!=1 {print $2}' | xargs kill`

**Comment by lukasito** [comment]
I had similar problem, that i wrapped my `java -jar ..` into sh script. The daemon killed the sh, but not the running java. Simply instead of setting commandLine to ./some.sh i changed it to `java` and pass necessary args like `-jar`, `path/to/lib.jar`. This solves my problem with living process left behind.

**Comment by mduft** [comment]
I have the same problem. unfortunately, the .sh has some complex logic which should be tested, so I cannot get rid of it. I would need a way to kill child processes along with the actual process..

We have some similar code in our own application...

```
    private void destroy(ProcessHandle process) {
        // First kill all processes that might be forked by the root
        process.descendants().forEach(ph -> {
            ph.destroy();
        });

        // Terminate the process itself
        process.destroy();
    }
```

**Comment by psxpaul** [comment]
I've added a test for this, but it seems to work for me. From googling around, this might be a platform specific issue - what OS and shell are people using when they encounter this issue? I've tested this on MacOS with bash 3.2.57, as well as Ubuntu with bash 5.0.3.

**Comment by mduft** [comment]
We're using gradle start scripts for a Java based server (.bat, shell script), interesting enough:

1. It's fully reproducible on Windows. It happens always that after the stop task, the .bat is gone, but the java process lives on.
2. Yesterday when I commented, it was fully reproducible on Fedora 29, bash 4.4.23. I then started to try and grab the process handle via all kinds of illegal tricks from the task ;) (btw. would be nice to have "semi-official" access to it). I was dissatisfied with the results (was not working xD), so I hard-resetted back to where I started - and bam, it's no longer reproducible. I have /no/ idea what happened, what changed (nothing IMHO), but it works (again) on linux now...

Our gradle task tries to ExecFork bin/bdeploy{.bat,} from here: https://github.com/bdeployteam/bdeploy/releases/tag/v1.2.1 - `bdeploy-win64-1.2.1.zip` and `bdeploy-linux64-1.2.1.zip` respectively.

Easily reproducible when cloning https://github.com/bdeployteam/bdeploy and running `gradlew releaseTest` which downloads and runs previous releases and tests upgrading to current - while doing so, the server is started in multiple old versions, and should go away /before/ the next one is launched - which is not happening on Windows.

**Comment by mduft** [comment]
I did some more googling and indeed the suggested method to make sure that child processes are destroyed as well is exactly the code I posted above, or put a little differently, this:

```
p.descendants().forEach(ph -> {
    ph.destroy();
});
p.destroy();
```
Could you maybe create an option to use this code instead of a plain single destroy? While at it, I would still appreciate a way to grab the actual process handle from the gradle script, so one could work around such issues in the meantime... :)

**Comment by davishyer** [comment]
The project that prompted my original post has taken a new approach, so I can't guarantee that my current environment would still encounter the issue. However, I'm also on MacOS (10.14.6 fwiw) and bash 3.2.57. Based on the reactions to the original post, I assume others have run into the issue and could provide better help :P

If the issue appears to no longer be encountered, I'm fine with closing this based on your testing @psxpaul. Thanks for looking into this by the way!

**Comment by psxpaul** [comment]
Thanks for your feedback @mduft. Unfortunately I don't have access to a windows machine, so I can't confirm any fixes will work for you. If you want to try the code snippet you posted, you can add it to `AbstractExecFork.stop()`. I have already added a test case for it in sample_projects/shell_script. After running a `./gradlew clean build`, you should see that no processes are still running and writing to sample_projects/shell_script/build/daemon.log.

I also imagine you'd want to recursively destroy all descendants, rather than just the first level.

**Comment by mduft** [comment]
Thanks for the suggestion, will try it ASAP. descendants() is already deep, children() would give use just direct children.

**Comment by mduft** [comment]
Is it acceptable to require Java 9? Otherwise the ProcessHandle API is not yet there and I guess it would be hard to call it xD I would have to use reflection to allow fixing the issue on 9+ while keeping <9 as is...
The alternative is to actually expose the process to gradle scripts so that consumers of the plugin can implement this on their own where required...
I have prepared two pull requests for this:

- https://github.com/psxpaul/gradle-execfork-plugin/pull/29 - add code to stop descendants, requires Java 9 for the plugin to be usable
- https://github.com/psxpaul/gradle-execfork-plugin/pull/30 - adapt code to expose process handle, requires Java 9 only for user which want to deal with descendants in their build.gradle

Both contain the commit to adapt the build and tests to windows.

**Comment by psxpaul** [comment]
That's a really good question. We still use jdk 8 quite a bit at my company, and I imagine that's true at a lot of places. The reflection approach sounds acceptable to me, if it's not too difficult.

**Comment by mduft** [comment]
I thought a little more on this, and I think the reflection approach is not such a wise idea: The problem is that the plugin will magically behave different on Java <9 and 9+ - something that I very much dislike in day-to-day work :) I can still try to come up with a reflective approach pull request as well if you want to.

**Comment by mduft** [comment]
Aaaand here we go: #31 

You may now choose any of the three pull requests :) #30 may even make sense with one of #29 or #31 applied, as it simply exposes the process handle...

All three pull requests are drafts, so you can choose which one is a good fit for your project :)

**Comment by mduft** [comment]
@psxpaul Did you have a few minutes already to look at those pull requests?

**Comment by psxpaul** [comment]
Hey thanks for the contributions @mduft! Sorry for the delay, but this is a busy time of year for me.

I think #31 looks good, but I do agree that different behavior between Java <9 and 9+ is not ideal. I'm thinking of merging that PR and adding a new killDescendants option (defaulting to true). If killDescendants==true and Java <9, then error out. That way, users on Java 8 can set killDescendants=false to maintain current behavior, but users on Java 9+ will see the new behavior by default.

**Comment by psxpaul** [comment]
I have published version 0.1.13 that adds the `killDescendants` option, enabled by default. Please let me know if this fixes the issue or not.

**Comment by mduft** [comment]
Thats great, thanks! I will test ASAP.

**Comment by mduft** [comment]
I tested it, and it works perfectly fine on Linux and Windows :) Thanks again! For me, this issue is solved.
